# Generated by Django 6.0.3 on 2026-03-22 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Used in URLs: cems.app/college-slug/', max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain if any, e.g. events.herald.edu.np', max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color for branding', max_length=7)),
                ('accent_color', models.CharField(default='#7c3aed', max_length=7)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='College contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('max_events', models.IntegerField(default=10, help_text='Max concurrent published events')),
                ('max_users', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['name'],
            },
        ),
    ]
