# Generated by Django 5.2.8 on 2026-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='max_events',
        ),
        migrations.RemoveField(
            model_name='college',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='college',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='college',
            name='trial_ends_at',
        ),
        migrations.AlterField(
            model_name='college',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
